package com.umc7th.a1grade.unittest.user.fake;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

import com.umc7th.a1grade.domain.user.entity.mapping.UserCharacter;
import com.umc7th.a1grade.domain.user.repository.UserCharacterRepository;

public class FakeUserCharacterRepository implements UserCharacterRepository {

  private final AtomicLong autoGeneratedId = new AtomicLong(1);
  private final List<UserCharacter> data = new ArrayList<>();

  @Override
  public UserCharacter save(UserCharacter userCharacter) {
    if (userCharacter.getId() == null || userCharacter.getId() == 0) {
      UserCharacter newUserCharacter =
          UserCharacter.builder()
              .id(autoGeneratedId.getAndIncrement())
              .user(userCharacter.getUser())
              .character(userCharacter.getCharacter())
              .build();
      data.add(newUserCharacter);
      return newUserCharacter;
    } else {
      data.removeIf(a -> a.getId().equals(userCharacter.getId()));
      data.add(userCharacter);
      return userCharacter;
    }
  }
}
