package com.umc7th.a1grade.unittest.user.fake;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import com.umc7th.a1grade.domain.character.entity.Character;
import com.umc7th.a1grade.domain.character.repository.CharacterRepository;

public class FakeCharacterRepository implements CharacterRepository {
  private final AtomicLong autoGeneratedId = new AtomicLong(1);
  private final List<Character> data = new ArrayList<>();

  @Override
  public Optional<Character> findById(Long characterId) {
    return Optional.empty();
  }

  @Override
  public List<Character> findAll() {
    return new ArrayList<>(data);
  }
}
